const state={contracts:JSON.parse(localStorage.getItem('contractMonitorData')||'[]'),selectedId:null};
const $=id=>document.getElementById(id), fields=['number','subject','projectName','counterparty','owner','startDate','actualEndDate','amount','currency','status','comment'];
const db=new Promise((resolve,reject)=>{const r=indexedDB.open('contractMonitorFiles',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function fileStore(mode,value){const d=await db;return new Promise((resolve,reject)=>{const t=d.transaction('files',mode==='get'?'readonly':'readwrite'),s=t.objectStore('files');const r=mode==='get'?s.get(value):mode==='delete'?s.delete(value.id):s.put(value);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
const save=()=>localStorage.setItem('contractMonitorData',JSON.stringify(state.contracts));
const iso=()=>new Date().toISOString().slice(0,10), days=date=>Math.ceil((new Date(`${date}T00:00:00`)-new Date(`${iso()}T00:00:00`))/86400000);
function control(item,threshold,complete){if(complete)return ['Завершено','done'];if(!item.date)return ['Нет даты','none'];const d=days(item.date);if(d<0)return ['Просрочено','overdue'];if(d<=threshold)return [`Скоро: ${d} дн.`,'soon'];return [`В срок: ${d} дн.`,'ok']}
function contractControl(c){return control({date:c.endDate},30,c.status==='Завершён'||!!c.actualEndDate)}
function milestoneControl(m){return control({date:m.date},14,m.status==='Завершено'||!!m.actualDate)}
function badge(label,kind){return `<span class="badge ${kind==='overdue'?'overdue':kind==='soon'?'soon':''}">${label}</span>`}
function q(v){return String(v||'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));}
function filtered(){const number=$('searchNumber').value.toLowerCase(),status=$('filterStatus').value,risk=$('filterRisk').value,owner=$('filterOwner').value.toLowerCase(),cp=$('filterCounterparty').value.toLowerCase();return state.contracts.filter(c=>{const cc=contractControl(c)[1],ms=(c.milestones||[]).map(m=>milestoneControl(m)[1]);return (!number||(c.number||'').toLowerCase().includes(number))&&(!status||c.status===status)&&(!owner||(c.owner||'').toLowerCase().includes(owner)||(c.milestones||[]).some(m=>(m.owner||'').toLowerCase().includes(owner)))&&(!cp||(c.counterparty||'').toLowerCase().includes(cp))&&(!risk||(risk==='docs'?(c.documents||[]).length:risk==='overdue'?(cc==='overdue'||ms.includes('overdue')):(cc==='soon'||ms.includes('soon'))));});}
function fillFilter(id,items,label){const select=$(id),current=select.value;select.innerHTML=`<option value="">${label}</option>`;[...new Set(items.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru')).forEach(item=>select.add(new Option(item,item)));select.value=[...select.options].some(o=>o.value===current)?current:''}
function fillNumbers(){const list=$('contractNumbers'),current=$('searchNumber').value;list.innerHTML='';[...new Set(state.contracts.map(c=>c.number).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru')).forEach(number=>list.append(new Option(number)));$('searchNumber').value=current;}
function render(){fillNumbers();fillFilter('filterOwner',state.contracts.flatMap(c=>[c.owner,...(c.milestones||[]).map(m=>m.owner)]),'Все ответственные');fillFilter('filterCounterparty',state.contracts.map(c=>c.counterparty),'Все контрагенты');
const all=state.contracts, ms=all.flatMap(c=>(c.milestones||[]).map(m=>({c,m}))), stat=(id,v)=>$(id).textContent=v;$('totalCount').textContent=all.length;stat('activeCount',all.filter(c=>c.status==='В работе').length);stat('completedCount',all.filter(c=>c.status==='Завершён').length);stat('overdueCount',all.filter(c=>contractControl(c)[1]==='overdue').length);stat('soonCount',all.filter(c=>contractControl(c)[1]==='soon').length);stat('milestoneOverdue',ms.filter(({m})=>milestoneControl(m)[1]==='overdue').length);stat('milestoneSoon',ms.filter(({m})=>milestoneControl(m)[1]==='soon').length);stat('unconfirmedCount',ms.filter(({m,c})=>m.status!=='Завершено'&&!(c.documents||[]).some(d=>d.milestoneId===m.id)).length);renderEvents();}
function renderEvents(){let events=[];state.contracts.forEach(c=>{if(c.endDate&&!['Завершён','Расторгнут'].includes(c.status))events.push({c,name:'Завершение договора',date:c.endDate,owner:c.owner,ctrl:contractControl(c)});(c.milestones||[]).forEach(m=>{if(m.date&&m.status!=='Завершено')events.push({c,name:m.name||'Без названия',date:m.date,owner:m.owner||c.owner,ctrl:milestoneControl(m)})})});events.sort((a,b)=>a.date.localeCompare(b.date));const box=$('events');box.innerHTML=events.slice(0,12).map(e=>`<tr><td>${q(e.c.number)}<br><small>${q(e.c.subject)}</small></td><td>${q(e.name)}</td><td>${e.date}</td><td>${days(e.date)} дн.</td><td>${q(e.owner)}</td><td>${badge(e.ctrl[0],e.ctrl[1])}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Событий с указанным плановым сроком пока нет.</td></tr>'}
function select(id){state.selectedId=id;const c=state.contracts.find(x=>x.id===id);$('emptyState').classList.add('hidden');$('contractForm').classList.remove('hidden');$('contractId').value=c.id;fields.forEach(k=>$(k).value=c[k]||'');$('formTitle').textContent=`Договор ${c.number||'без номера'}`;const [label,kind]=contractControl(c);$('contractRisk').innerHTML=`Контроль срока: ${badge(label,kind)}`;$('updatedAt').textContent=c.updatedAt?`Обновлено: ${new Date(c.updatedAt).toLocaleString('ru-RU')}`:'';renderMilestones(c);renderDocuments(c);render();}
function renderMilestones(c){const box=$('milestoneList');box.innerHTML='';(c.milestones||[]).forEach(m=>addMilestone(m));const select=$('docMilestone');select.innerHTML='<option value="">К договору в целом</option>';(c.milestones||[]).forEach(m=>select.add(new Option(m.name||'Без названия',m.id)));}
function addMilestone(m={id:crypto.randomUUID(),name:'',type:'Промежуточный этап',date:'',actualDate:'',status:'Не начато',owner:'',comment:''}){const n=$('milestoneTemplate').content.firstElementChild.cloneNode(true);for(const [cl,key] of [['.m-name','name'],['.m-type','type'],['.m-date','date'],['.m-actual-date','actualDate'],['.m-status','status'],['.m-owner','owner'],['.m-comment','comment']])n.querySelector(cl).value=m[key]||'';n.dataset.id=m.id;const setRisk=()=>{const val={date:n.querySelector('.m-date').value,status:n.querySelector('.m-status').value,actualDate:n.querySelector('.m-actual-date').value},r=milestoneControl(val);n.querySelector('.m-risk').textContent=`Контроль: ${r[0]}`};n.querySelectorAll('input,select').forEach(x=>x.onchange=setRisk);setRisk();n.querySelector('.remove').onclick=()=>{if(confirm('Удалить веху?'))n.remove()};$('milestoneList').append(n)}
function milestones(){return [...document.querySelectorAll('.milestone')].map(n=>({id:n.dataset.id,name:n.querySelector('.m-name').value,type:n.querySelector('.m-type').value,date:n.querySelector('.m-date').value,actualDate:n.querySelector('.m-actual-date').value,status:n.querySelector('.m-status').value,owner:n.querySelector('.m-owner').value,comment:n.querySelector('.m-comment').value})).filter(m=>m.name||m.date)}
async function renderDocuments(c){const box=$('documentList');box.innerHTML='';for(const doc of c.documents||[]){const el=document.createElement('div');el.className='document';const target=doc.milestoneId?(c.milestones||[]).find(m=>m.id===doc.milestoneId)?.name||'Удалённая веха':'Договор';el.innerHTML=`<div><b>${q(doc.name)}</b><small>${q(target)} · ${new Date(doc.added).toLocaleDateString('ru-RU')} · ${Math.ceil(doc.size/1024)} КБ</small></div><div class="document-actions"><a href="#">Открыть</a><button type="button" class="text-danger">Удалить</button></div>`;el.querySelector('a').onclick=async e=>{e.preventDefault();const f=await fileStore('get',doc.id);if(f)window.open(URL.createObjectURL(f.blob),'_blank')};el.querySelector('button').onclick=async()=>{if(!confirm(`Удалить файл «${doc.name}»?`))return;await fileStore('delete',doc);c.documents=c.documents.filter(d=>d.id!==doc.id);save();renderDocuments(c);render()};box.append(el)}}
function applyFilters(){const match=filtered()[0];if(match)select(match.id);else{state.selectedId=null;$('contractForm').classList.add('hidden');$('emptyState').classList.remove('hidden');render();}}
$('newContract').onclick=()=>{const c={id:crypto.randomUUID(),number:'',subject:'',projectName:'',counterparty:'',owner:'',startDate:'',actualEndDate:'',amount:'',currency:'RUB',status:'В работе',comment:'',milestones:[],documents:[],updatedAt:Date.now()};state.contracts.unshift(c);save();select(c.id)};$('addMilestone').onclick=()=>addMilestone();$('searchNumber').oninput=applyFilters;['filterStatus','filterRisk','filterOwner','filterCounterparty'].forEach(id=>$(id).oninput=applyFilters);
$('contractForm').onsubmit=e=>{e.preventDefault();const c=state.contracts.find(x=>x.id===$('contractId').value);fields.forEach(k=>c[k]=$(k).value);c.milestones=milestones();c.updatedAt=Date.now();save();select(c.id)};$('fileInput').onchange=async e=>{const c=state.contracts.find(x=>x.id===state.selectedId);for(const blob of e.target.files){const id=crypto.randomUUID();await fileStore('put',{id,blob});c.documents.push({id,name:blob.name,size:blob.size,added:Date.now(),milestoneId:$('docMilestone').value})}save();e.target.value='';renderDocuments(c);render()};$('deleteContract').onclick=async()=>{const c=state.contracts.find(x=>x.id===state.selectedId);if(!confirm(`Удалить договор «${c.number||'без номера'}» и все его документы?`))return;for(const doc of c.documents||[])await fileStore('delete',doc);state.contracts=state.contracts.filter(x=>x.id!==c.id);state.selectedId=null;save();$('contractForm').classList.add('hidden');$('emptyState').classList.remove('hidden');render()};render();
